# Generated by Django 4.0.6 on 2022-07-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='last_run_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='next_run_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='run_count',
        ),
    ]
