# Generated by Django 4.0.6 on 2022-07-22 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_group_through', to='scheduler.task')),
            ],
            options={
                'ordering': ['task_group'],
            },
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='tasks',
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='tasks',
            field=models.ManyToManyField(related_name='tasks', through='scheduler.TaskGroupTask', to='scheduler.task'),
        ),
        migrations.AddField(
            model_name='taskgrouptask',
            name='task_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_group_through', to='scheduler.taskgroup'),
        ),
    ]
