# Generated by Django 4.0.6 on 2022-07-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
