# Generated by Django 4.0.6 on 2022-07-15 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_task_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='recur_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.timeperiod'),
        ),
    ]
