# Generated by Django 4.0.6 on 2022-09-05 13:38
import datetime

from django.db import migrations, models
import django.db.models.deletion
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_job_last_run_time_remove_job_next_run_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='engineer',
            field=models.ForeignKey(blank=True, help_text='Optional', null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.engineer'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,
                                       default=datetime.datetime(2022, 10, 6, 13, 24, 0, 833042, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
