# Generated by Django 4.0.6 on 2022-09-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_job_last_run_time_remove_job_next_run_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='engineer',
            field=models.ForeignKey(blank=True, help_text='Optional', null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.engineer'),
        ),
    ]
