# Generated by Django 4.0.6 on 2022-10-06 13:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_job_engineer'),
    ]

    operations = [

    ]
