# Generated by Django 4.0.6 on 2022-07-22 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_rename_taskgrouptask_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='end_date',
        ),
        migrations.AddField(
            model_name='job',
            name='run_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='engineer',
            field=models.ForeignKey(help_text='Optional', null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.engineer'),
        ),
    ]
