# Generated by Django 3.2 on 2022-10-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_job_created_at_job_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reoccurrence_day',
            field=models.CharField(default='0', help_text='Asterix(*) represents all, comma seperates multiple, IE. "1,10,15" would represent the 1st, 10th and 15th day of the month ', max_length=32),
        ),
        migrations.AddField(
            model_name='task',
            name='reoccurrence_month',
            field=models.CharField(default='0', help_text='Asterix(*) represents all, comma seperates multiple, IE. "3,6,9,12" would represent Jan, June, Sep and Dec ', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='recur_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.timeperiod'),
        ),
    ]
