# Generated by Django 4.0.6 on 2022-07-15 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_company_id_alter_engineer_id_alter_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='freshdesk_id',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='engineer',
            name='freshdesk_id',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='group',
            name='freshdesk_id',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='recur_period',
            field=models.ForeignKey(help_text='If monthly, task will be created on the same day (1st -> 1st), weekly or bi-weekly - same week day (Monday -> Monday)', on_delete=django.db.models.deletion.CASCADE, to='scheduler.timeperiod'),
        ),
    ]
