# Generated by Django 4.0.6 on 2022-07-20 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_company_freshdesk_id_engineer_freshdesk_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='company',
        ),
        migrations.RemoveField(
            model_name='task',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_run_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recur_period',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.task')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_time', models.DateTimeField(null=True)),
                ('next_run_time', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.company')),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.engineer')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.group')),
                ('recur_period', models.ForeignKey(help_text='If monthly, task will be created on the same day (IE. 1st -> 1st), if weekly or bi-weekly it will be the same week day (IE. Monday -> Monday)', on_delete=django.db.models.deletion.CASCADE, to='scheduler.timeperiod')),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.taskgroup')),
            ],
        ),
    ]
