# Generated by Django 4.0.9 on 2023-07-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20221024_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reoccurrence_day_of_week',
            field=models.CharField(default='0', help_text='Asterix(*) represents all, comma seperates multiple, IE. "1,10,15" would represent the 1st, 10th and 15th day of the month', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='reoccurrence_day',
            field=models.CharField(default='0', help_text='Asterix(*) represents all, comma seperates multiple, IE. "1,10,15" would represent the 1st, 10th and 15th day of the month', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='reoccurrence_month',
            field=models.CharField(default='0', help_text='Asterix(*) represents all, comma seperates multiple, IE. "3,6,9,12" would represent March, June, Sep and Dec', max_length=32),
        ),
    ]
