# Generated by Django 4.0.9 on 2023-07-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_task_reoccurrence_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reoccurrence_day_of_week',
            field=models.CharField(default='0', help_text='Asterix(*) represents all, comma seperates multiple, IE. "1,3,5" would represent Monday, Wednesday and Friday.', max_length=32),
        ),
    ]
