# Generated by Django 4.0.9 on 2023-07-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_alter_task_reoccurrence_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='reoccurrence_day',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='reoccurrence_day_of_week',
            new_name='day_of_week',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='reoccurrence_month',
            new_name='month',
        ),
    ]
