# Generated by Django 4.0.9 on 2023-07-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_rename_reoccurrence_day_task_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrunhistory',
            name='company',
            field=models.CharField(default='unknown', max_length=128),
            preserve_default=False,
        ),
    ]
